nome = str(input("Digite o seu nome:")
idade = int(input("Digite a sua idade:")
altura = float(input("Digite a sua altura:")
imc = peso / (altura ** 2)
print(f"Nome: {nome}")
print(f"Idade: {idade} anos")
print(f"Peso: {peso} kg")
print(f"Altura: {altura} m")
print(f"IMC: {imc:.2f}")
print(f"{nome} tem {idade} anos, pesa {peso} kg e tem {altura} de altura. Seu IMC é {imc:.2f}.")
